site_name: Your Site Name

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.integrate

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Usage: guide/usage.md
  - API:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
  - About: about.md